"""
评分卡文档导出模块
支持PDF/Excel/HTML/Python脚本导出
"""
import pandas as pd
import numpy as np
from typing import Dict, List, Any
import json
import io


class ScorecardExporter:
    """评分卡文档导出"""

    def __init__(self, scorecard: List[Dict], train_metrics: Dict, test_metrics: Dict,
                 coef: Dict, intercept: float, base_score: int, pdo: int,
                 data_summary: Dict, woe_summary: Dict):
        self.scorecard = scorecard
        self.train_metrics = train_metrics
        self.test_metrics = test_metrics
        self.coef = coef
        self.intercept = intercept
        self.base_score = base_score
        self.pdo = pdo
        self.data_summary = data_summary
        self.woe_summary = woe_summary

    def export_html(self) -> str:
        """导出HTML报告"""
        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>信用风险评分卡模型文档</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1e293b; line-height: 1.6; }}
h1 {{ text-align: center; color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }}
h2 {{ color: #2563eb; margin-top: 2rem; border-left: 4px solid #2563eb; padding-left: 0.75rem; }}
h3 {{ color: #475569; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th {{ background: #2563eb; color: white; padding: 0.5rem; text-align: left; }}
td {{ padding: 0.5rem; border-bottom: 1px solid #e2e8f0; }}
tr:nth-child(even) {{ background: #f8fafc; }}
.metric {{ display: inline-block; background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 0.5rem 1rem; margin: 0.25rem; }}
.metric strong {{ color: #2563eb; font-size: 1.2em; }}
.pos-score {{ color: #059669; font-weight: bold; }}
.neg-score {{ color: #dc2626; font-weight: bold; }}
.cover {{ text-align: center; margin-bottom: 2rem; }}
.cover p {{ color: #64748b; }}
</style>
</head>
<body>
<div class="cover">
<h1>信用风险评分卡模型文档</h1>
<p>{self.data_summary.get('total_samples', 'N/A')} samples · {self.data_summary.get('num_features', 'N/A')} features · v0.1_baseline</p>
<p>Generated by Risk Modeling Assistant</p>
</div>

<h2>1. 数据集概览</h2>
<table>
<tr><th>项目</th><th>值</th></tr>
<tr><td>总样本数</td><td>{self.data_summary.get('total_samples', 'N/A')}</td></tr>
<tr><td>特征数量</td><td>{self.data_summary.get('num_features', 'N/A')}</td></tr>
<tr><td>好客户数</td><td>{self.data_summary.get('good_count', 'N/A')} ({self.data_summary.get('good_rate', 0)*100:.1f}%)</td></tr>
<tr><td>坏客户数</td><td>{self.data_summary.get('bad_count', 'N/A')} ({self.data_summary.get('bad_rate', 0)*100:.1f}%)</td></tr>
</table>

<h2>2. 评分卡表</h2>
<table>
<tr><th>特征</th><th>分箱</th><th>WOE</th><th>系数</th><th>加减分</th></tr>
"""
        for item in self.scorecard:
            score_cls = "pos-score" if item["score"] >= 0 else "neg-score"
            html += f"""<tr><td>{item['feature']}</td><td>{item['bin']}</td><td>{item['woe']}</td><td>{item['coef']}</td><td class="{score_cls}">{item['score']:+.1f}</td></tr>\n"""
        html += f"""</table>

<h2>3. 模型系数</h2>
<table>
<tr><th>特征</th><th>系数</th></tr>
"""
        for k, v in self.coef.items():
            html += f"<tr><td>{k}</td><td>{v:.6f}</td></tr>\n"
        html += f"""<tr><td>截距</td><td>{self.intercept:.6f}</td></tr>
</table>

<h2>4. 评估指标</h2>
<div>
"""
        for key, val in self.train_metrics.items():
            if isinstance(val, (int, float)):
                html += f'<span class="metric">训练 {key}: <strong>{val}</strong></span>\n'
        for key, val in self.test_metrics.items():
            if isinstance(val, (int, float)):
                html += f'<span class="metric">测试 {key}: <strong>{val}</strong></span>\n'
        html += f"""
</div>

<h2>5. 评分卡配置</h2>
<table>
<tr><th>参数</th><th>值</th></tr>
<tr><td>基础分</td><td>{self.base_score}</td></tr>
<tr><td>PDO</td><td>{self.pdo}</td></tr>
<tr><td>低风险阈值</td><td>≥660 自动通过</td></tr>
<tr><td>标准阈值</td><td>580-659 标准通过</td></tr>
<tr><td>人工审核</td><td>500-579 人工审核</td></tr>
<tr><td>拒绝阈值</td><td>&lt;500 自动拒绝</td></tr>
</table>

<h2>6. 授信策略建议</h2>
<p>推荐授信阈值 <strong>580分</strong>。分层策略：</p>
<ul>
<li><strong>≥660分</strong>：自动通过，低风险客户</li>
<li><strong>580-659分</strong>：标准通过，正常授信</li>
<li><strong>500-579分</strong>：人工审核，需人工复核</li>
<li><strong>&lt;500分</strong>：自动拒绝，高风险客户</li>
</ul>
</body>
</html>"""
        return html

    def export_excel(self) -> bytes:
        """导出Excel评分卡"""
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine="openpyxl") as writer:
            pd.DataFrame(self.scorecard).to_excel(writer, sheet_name="评分卡表", index=False)
            pd.DataFrame(
                [{"feature": k, "coef": v} for k, v in self.coef.items()]
            ).to_excel(writer, sheet_name="模型系数", index=False)
            metrics_df = pd.DataFrame([self.train_metrics, self.test_metrics], index=["训练集", "测试集"])
            metrics_df.to_excel(writer, sheet_name="评估指标")
            summary_df = pd.DataFrame([{
                "基础分": self.base_score,
                "PDO": self.pdo,
                "总样本": self.data_summary.get("total_samples"),
                "特征数": self.data_summary.get("num_features"),
                "好客户率": self.data_summary.get("good_rate"),
                "坏客户率": self.data_summary.get("bad_rate"),
            }])
            summary_df.to_excel(writer, sheet_name="模型概览", index=False)
        return output.getvalue()

    def export_python(self) -> str:
        """导出Python评分卡脚本"""
        scorecard_json = json.dumps(self.scorecard, ensure_ascii=False, indent=2)
        coef_json = json.dumps({k: round(v, 6) for k, v in self.coef.items()}, indent=2)
        return f'''"""
信用风险评分卡 - Python部署脚本
自动生成，可直接用于生产环境
"""
import numpy as np
import json

BASE_SCORE = {self.base_score}
PDO = {self.pdo}
INTERCEPT = {self.intercept:.6f}
COEF = {coef_json}
SCORECARD = {scorecard_json}

def calculate_score(features: dict) -> dict:
    """计算客户信用评分"""
    score = BASE_SCORE
    breakdown = []
    for item in SCORECARD:
        feature = item["feature"]
        if feature in features:
            score += item["score"]
            breakdown.append({{
                "feature": feature,
                "bin": item["bin"],
                "score": item["score"],
            }})
    risk_level = "low_risk" if score >= 660 else "medium_risk" if score >= 580 else "high_risk" if score >= 500 else "very_high_risk"
    decision = "approve" if score >= 580 else "reject"
    return {{
        "score": int(round(score)),
        "risk_level": risk_level,
        "decision": decision,
        "threshold": 580,
        "breakdown": breakdown,
    }}

# 使用示例
if __name__ == "__main__":
    sample = {{"checking_status": "no checking", "duration": 12, "credit_amount": 2000}}
    result = calculate_score(sample)
    print(json.dumps(result, indent=2, ensure_ascii=False))
'''

    def export_sql(self) -> str:
        """导出SQL规则"""
        lines = ["-- 信用评分卡 SQL 规则", "-- 自动生成，可直接嵌入决策引擎", ""]
        for item in self.scorecard:
            lines.append(f"-- {item['feature']}: {item['bin']} -> {item['score']:+.1f}")
        lines.append("")
        lines.append("SELECT")
        lines.append(f"  {self.base_score}")
        for item in self.scorecard:
            lines.append(f"  + CASE WHEN {item['feature']} = '{item['bin']}' THEN {item['score']:.1f} ELSE 0 END")
        lines.append("  AS credit_score")
        lines.append("FROM customer_applications;")
        return "\n".join(lines)
